### ISSUE TITLE
Having Difficulty in Running my First Calculation

### ISSUE THREAD

**Issue by hcut** [richard-evans/vampire#104]
Hi,

I have installed the vampire on Linux through binary as well as source codes, but now I am wondering how to run the first calculation.
There are two files named input and Co.mat, and I ran these as executables, then it gave the following errors.

        computer@linux$ ./input 
       ./input: line 10: dimensions:unit-cell-size: command not found
       ./input: line 11: dimensions:system-size-x: command not found
       ./input: line 12: dimensions:system-size-y: command not found
       ./input: line 13: dimensions:system-size-z: command not found....

Kindly help us.

**Comment by richard-evans** [comment]
You need to run the executable: ./vampire-serial

**Comment by hcut** [comment]
Thank you very much
