### ISSUE TITLE
Second Vampire workshop slides

### ISSUE THREAD

**Issue by Fellow-baka** [richard-evans/vampire#39]
Dear Richard,

Unfortunately I was not able to visit workshop.
Is it it possible to put slides for the seconds workshop to [site](https://vampire.york.ac.uk/workshop/) as it was done for the first one?

**Comment by richard-evans** [comment]
Yes these are already available here

https://github.com/richard-evans/vampire-workshop

All the best,

Richard

**Comment by Fellow-baka** [comment]
Thanks!
