### ISSUE TITLE
missing control statement 'sim:monte-carlo-algorithm' in version 6.0.0

### ISSUE THREAD

**Issue by NitroAshi** [richard-evans/vampire#70]
In version 6.0.0, the control statement 'sim:monte-carlo-algorithm' can not set in the input file.
the error is "Error - Unknown control statement 'sim:monte-carlo-algorithm' on line 49 of input file
Fatal error: Aborting program. See log file for details."

**Comment by richard-evans** [comment]
Sorry the manual needs updating. This was refactored and now you can set: monte-carlo:algorithm = adaptive

**Comment by NitroAshi** [comment]
> 

Thank you! the statement "montecarlo:algorithm" works.
