### ISSUE TITLE
Checkpoints and mean values

### ISSUE THREAD

**Issue by milton-persson** [richard-evans/vampire#72]
Whenever I load checkpoint files there is a jump in the data for any mean, like mean-magnetisation-length. The image attached shows the example in tests/time-series/, slightly modified, stopped twice and continued from checkpoint files, at the kinks in the mean-magnetisation-length. 
![checkpoint-test](https://user-images.githubusercontent.com/55807898/150660450-519525e7-bce6-4b23-8b25-884d218d0341.png)

It seems the data counter (stats::data_counter) is reset even when checkpoint files are loaded, or just initialized to 0. I can't quite figure it out but it would be great if this could be fixed soon.

Input and material file: (had to change the extension to upload them)
[input.txt](https://github.com/richard-evans/vampire/files/7919560/input.txt)
[Co.txt](https://github.com/richard-evans/vampire/files/7919562/Co.txt)

**Comment by richard-evans** [comment]
Yes this was an oversight! I've added support for magnetisation, specific heat and susceptibility in the latest develop branch, so for a continued simulation the averages are kept. These are also still compatible with older checkpoints.
