### ISSUE TITLE
unit cell creation from ucf ignores the rest of materials multi-material ucf (develop branch)

### ISSUE THREAD

**Issue by mahdawi** [richard-evans/vampire#89]
On the develop branch, when creating  a multi-element crystal using a ucf file (such as an AFM material), vampire keeps only the first material and discards the rest.
An example is the attached output of  "3c_antiferromagnets" in the workshop.
[output.txt](https://github.com/richard-evans/vampire/files/10058036/output.txt)

**Comment by richard-evans** [comment]
Yes - you need to use 
material[1]unit-cell-category = 1
material[2]unit-cell-category = 2
to associate materials in the unit cell file to materials in the material file. The reason for not doing this automatically is that often you want multiple materials associated with the same lattice site (material) in the unit cell file.

**Comment by mahdawi** [comment]
Thanks!
